// src/data/vocabularyData.js

export const VOCABULARY_CATEGORIES = [
  { id: 'food', name: 'Food & Dining', icon: '🍽️', color: 'bg-orange-500/20 text-orange-400' },
  { id: 'travel', name: 'Travel & Transportation', icon: '✈️', color: 'bg-blue-500/20 text-blue-400' },
  { id: 'business', name: 'Business & Work', icon: '💼', color: 'bg-purple-500/20 text-purple-400' },
  { id: 'daily', name: 'Daily Life', icon: '🏠', color: 'bg-green-500/20 text-green-400' },
  { id: 'emotions', name: 'Emotions & Feelings', icon: '😊', color: 'bg-pink-500/20 text-pink-400' },
  { id: 'health', name: 'Health & Body', icon: '🏥', color: 'bg-red-500/20 text-red-400' },
  { id: 'technology', name: 'Technology', icon: '💻', color: 'bg-indigo-500/20 text-indigo-400' },
  { id: 'education', name: 'Education', icon: '📚', color: 'bg-yellow-500/20 text-yellow-400' },
  { id: 'nature', name: 'Nature & Weather', icon: '🌳', color: 'bg-teal-500/20 text-teal-400' },
  { id: 'entertainment', name: 'Entertainment', icon: '🎬', color: 'bg-rose-500/20 text-rose-400' },
];

export const vocabularyData = [
  // FOOD & DINING (20 words)
  { id: 1, term: 'Restaurant', definition: 'A place where meals are served to customers', example: 'We ate dinner at a nice restaurant', category: 'food', difficulty: 'beginner' },
  { id: 2, term: 'Menu', definition: 'A list of dishes available at a restaurant', example: 'Can I see the menu, please?', category: 'food', difficulty: 'beginner' },
  { id: 3, term: 'Appetizer', definition: 'A small dish served before the main meal', example: 'We ordered soup as an appetizer', category: 'food', difficulty: 'intermediate' },
  { id: 4, term: 'Dessert', definition: 'Sweet food eaten at the end of a meal', example: 'Would you like dessert?', category: 'food', difficulty: 'beginner' },
  { id: 5, term: 'Vegetarian', definition: 'A person who does not eat meat', example: 'Do you have vegetarian options?', category: 'food', difficulty: 'intermediate' },
  { id: 6, term: 'Recipe', definition: 'Instructions for cooking a dish', example: 'This is my grandmother\'s recipe', category: 'food', difficulty: 'beginner' },
  { id: 7, term: 'Ingredients', definition: 'Items needed to make a dish', example: 'What ingredients do I need?', category: 'food', difficulty: 'intermediate' },
  { id: 8, term: 'Spicy', definition: 'Having a hot, pungent taste', example: 'This curry is too spicy for me', category: 'food', difficulty: 'beginner' },
  { id: 9, term: 'Delicious', definition: 'Very pleasant to taste', example: 'The food was absolutely delicious', category: 'food', difficulty: 'beginner' },
  { id: 10, term: 'Reservation', definition: 'Booking a table in advance', example: 'I made a reservation for 7pm', category: 'food', difficulty: 'intermediate' },
  { id: 11, term: 'Waiter', definition: 'Person who serves food in a restaurant', example: 'The waiter brought our drinks', category: 'food', difficulty: 'beginner' },
  { id: 12, term: 'Bill', definition: 'Statement of money owed for a meal', example: 'Can we have the bill, please?', category: 'food', difficulty: 'beginner' },
  { id: 13, term: 'Portion', definition: 'Amount of food served to one person', example: 'The portions here are huge', category: 'food', difficulty: 'intermediate' },
  { id: 14, term: 'Cuisine', definition: 'Style of cooking from a region', example: 'I love Italian cuisine', category: 'food', difficulty: 'intermediate' },
  { id: 15, term: 'Fresh', definition: 'Recently made or obtained', example: 'They use fresh ingredients daily', category: 'food', difficulty: 'beginner' },
  { id: 16, term: 'Beverage', definition: 'Any drink', example: 'What beverages do you have?', category: 'food', difficulty: 'intermediate' },
  { id: 17, term: 'Leftovers', definition: 'Food remaining after a meal', example: 'Can I take the leftovers home?', category: 'food', difficulty: 'intermediate' },
  { id: 18, term: 'Chef', definition: 'Professional cook', example: 'The chef prepared a special dish', category: 'food', difficulty: 'beginner' },
  { id: 19, term: 'Buffet', definition: 'Meal with many dishes to choose from', example: 'The hotel has a breakfast buffet', category: 'food', difficulty: 'intermediate' },
  { id: 20, term: 'Takeout', definition: 'Food ordered to eat elsewhere', example: 'Let\'s get Chinese takeout tonight', category: 'food', difficulty: 'beginner' },

  // TRAVEL & TRANSPORTATION (20 words)
  { id: 21, term: 'Airport', definition: 'Place where planes take off and land', example: 'I need to get to the airport by 6am', category: 'travel', difficulty: 'beginner' },
  { id: 22, term: 'Passport', definition: 'Official travel document', example: 'Don\'t forget your passport', category: 'travel', difficulty: 'beginner' },
  { id: 23, term: 'Boarding Pass', definition: 'Ticket to board a plane', example: 'Show your boarding pass at the gate', category: 'travel', difficulty: 'intermediate' },
  { id: 24, term: 'Luggage', definition: 'Bags and suitcases for travel', example: 'How many pieces of luggage do you have?', category: 'travel', difficulty: 'beginner' },
  { id: 25, term: 'Destination', definition: 'Place you are traveling to', example: 'What\'s your final destination?', category: 'travel', difficulty: 'intermediate' },
  { id: 26, term: 'Flight', definition: 'Journey by airplane', example: 'My flight leaves at 3pm', category: 'travel', difficulty: 'beginner' },
  { id: 27, term: 'Hotel', definition: 'Place providing lodging', example: 'We booked a hotel near the beach', category: 'travel', difficulty: 'beginner' },
  { id: 28, term: 'Reservation', definition: 'Booking in advance', example: 'I have a reservation under Smith', category: 'travel', difficulty: 'intermediate' },
  { id: 29, term: 'Taxi', definition: 'Car you pay to ride in', example: 'Let\'s take a taxi to the station', category: 'travel', difficulty: 'beginner' },
  { id: 30, term: 'Subway', definition: 'Underground train system', example: 'The subway is the fastest way', category: 'travel', difficulty: 'beginner' },
  { id: 31, term: 'Delay', definition: 'Late departure or arrival', example: 'The flight has a 2-hour delay', category: 'travel', difficulty: 'intermediate' },
  { id: 32, term: 'Tourist', definition: 'Person traveling for pleasure', example: 'Many tourists visit in summer', category: 'travel', difficulty: 'beginner' },
  { id: 33, term: 'Itinerary', definition: 'Planned route or schedule', example: 'Here\'s our travel itinerary', category: 'travel', difficulty: 'advanced' },
  { id: 34, term: 'Customs', definition: 'Border control for goods', example: 'Go through customs after baggage claim', category: 'travel', difficulty: 'intermediate' },
  { id: 35, term: 'Visa', definition: 'Permission to enter a country', example: 'Do I need a visa for France?', category: 'travel', difficulty: 'intermediate' },
  { id: 36, term: 'Sightseeing', definition: 'Visiting tourist attractions', example: 'We went sightseeing in Paris', category: 'travel', difficulty: 'beginner' },
  { id: 37, term: 'Roundtrip', definition: 'Journey to a place and back', example: 'I need a roundtrip ticket', category: 'travel', difficulty: 'intermediate' },
  { id: 38, term: 'Platform', definition: 'Where trains arrive and depart', example: 'The train leaves from platform 3', category: 'travel', difficulty: 'intermediate' },
  { id: 39, term: 'Accommodation', definition: 'Place to stay overnight', example: 'We need to book accommodation', category: 'travel', difficulty: 'advanced' },
  { id: 40, term: 'Directions', definition: 'Instructions on how to get somewhere', example: 'Can you give me directions?', category: 'travel', difficulty: 'beginner' },

  // BUSINESS & WORK (20 words)
  { id: 41, term: 'Meeting', definition: 'Gathering for discussion', example: 'We have a meeting at 10am', category: 'business', difficulty: 'beginner' },
  { id: 42, term: 'Deadline', definition: 'Time by which something must be done', example: 'The deadline is Friday', category: 'business', difficulty: 'intermediate' },
  { id: 43, term: 'Colleague', definition: 'Person you work with', example: 'She\'s my colleague from marketing', category: 'business', difficulty: 'intermediate' },
  { id: 44, term: 'Presentation', definition: 'Formal talk to an audience', example: 'I have to give a presentation tomorrow', category: 'business', difficulty: 'intermediate' },
  { id: 45, term: 'Contract', definition: 'Legal agreement', example: 'Please sign the contract', category: 'business', difficulty: 'intermediate' },
  { id: 46, term: 'Client', definition: 'Person who uses services', example: 'Our clients are very satisfied', category: 'business', difficulty: 'intermediate' },
  { id: 47, term: 'Resume', definition: 'Document listing work experience', example: 'Send me your resume', category: 'business', difficulty: 'intermediate' },
  { id: 48, term: 'Interview', definition: 'Meeting to assess suitability', example: 'I have a job interview next week', category: 'business', difficulty: 'beginner' },
  { id: 49, term: 'Salary', definition: 'Regular payment for work', example: 'What salary are you expecting?', category: 'business', difficulty: 'intermediate' },
  { id: 50, term: 'Promotion', definition: 'Advancement to higher position', example: 'She got a promotion last month', category: 'business', difficulty: 'intermediate' },
  { id: 51, term: 'Budget', definition: 'Planned spending limit', example: 'We need to stay within budget', category: 'business', difficulty: 'intermediate' },
  { id: 52, term: 'Profit', definition: 'Money gained after expenses', example: 'The company made a good profit', category: 'business', difficulty: 'intermediate' },
  { id: 53, term: 'Investment', definition: 'Money put into something for profit', example: 'This is a smart investment', category: 'business', difficulty: 'advanced' },
  { id: 54, term: 'Negotiation', definition: 'Discussion to reach agreement', example: 'The negotiation went well', category: 'business', difficulty: 'advanced' },
  { id: 55, term: 'Memo', definition: 'Written message in business', example: 'Please read the memo carefully', category: 'business', difficulty: 'intermediate' },
  { id: 56, term: 'Agenda', definition: 'List of meeting topics', example: 'What\'s on today\'s agenda?', category: 'business', difficulty: 'intermediate' },
  { id: 57, term: 'Conference', definition: 'Large formal meeting', example: 'I\'m attending a conference in Boston', category: 'business', difficulty: 'intermediate' },
  { id: 58, term: 'Partnership', definition: 'Business relationship', example: 'We formed a partnership', category: 'business', difficulty: 'advanced' },
  { id: 59, term: 'Strategy', definition: 'Plan to achieve goals', example: 'Our marketing strategy is working', category: 'business', difficulty: 'advanced' },
  { id: 60, term: 'Revenue', definition: 'Total income from business', example: 'Revenue increased this quarter', category: 'business', difficulty: 'advanced' },

  // DAILY LIFE (20 words)
  { id: 61, term: 'Routine', definition: 'Regular way of doing things', example: 'This is my morning routine', category: 'daily', difficulty: 'beginner' },
  { id: 62, term: 'Chores', definition: 'Regular household tasks', example: 'I have to do my chores', category: 'daily', difficulty: 'beginner' },
  { id: 63, term: 'Grocery', definition: 'Food and household items', example: 'I need to buy groceries', category: 'daily', difficulty: 'beginner' },
  { id: 64, term: 'Laundry', definition: 'Washing clothes', example: 'I need to do the laundry', category: 'daily', difficulty: 'beginner' },
  { id: 65, term: 'Appointment', definition: 'Scheduled meeting', example: 'I have a dentist appointment', category: 'daily', difficulty: 'intermediate' },
  { id: 66, term: 'Schedule', definition: 'Planned activities', example: 'What\'s your schedule today?', category: 'daily', difficulty: 'intermediate' },
  { id: 67, term: 'Neighbor', definition: 'Person living nearby', example: 'My neighbor is very friendly', category: 'daily', difficulty: 'beginner' },
  { id: 68, term: 'Bills', definition: 'Money owed for services', example: 'I need to pay my bills', category: 'daily', difficulty: 'beginner' },
  { id: 69, term: 'Rent', definition: 'Payment for housing', example: 'Rent is due on the first', category: 'daily', difficulty: 'beginner' },
  { id: 70, term: 'Furniture', definition: 'Items like chairs and tables', example: 'We need new furniture', category: 'daily', difficulty: 'beginner' },
  { id: 71, term: 'Utilities', definition: 'Services like water and electricity', example: 'Utilities are included in rent', category: 'daily', difficulty: 'intermediate' },
  { id: 72, term: 'Cleaning', definition: 'Making something clean', example: 'The house needs cleaning', category: 'daily', difficulty: 'beginner' },
  { id: 73, term: 'Shopping', definition: 'Buying goods', example: 'Let\'s go shopping this weekend', category: 'daily', difficulty: 'beginner' },
  { id: 74, term: 'Commute', definition: 'Daily travel to work', example: 'My commute takes 30 minutes', category: 'daily', difficulty: 'intermediate' },
  { id: 75, term: 'Errands', definition: 'Short trips for tasks', example: 'I have to run some errands', category: 'daily', difficulty: 'intermediate' },
  { id: 76, term: 'Hobbies', definition: 'Activities done for pleasure', example: 'What are your hobbies?', category: 'daily', difficulty: 'beginner' },
  { id: 77, term: 'Exercise', definition: 'Physical activity', example: 'I exercise every morning', category: 'daily', difficulty: 'beginner' },
  { id: 78, term: 'Alarm', definition: 'Device that makes noise at set time', example: 'Set your alarm for 7am', category: 'daily', difficulty: 'beginner' },
  { id: 79, term: 'Remote', definition: 'Device to control electronics', example: 'Where\'s the TV remote?', category: 'daily', difficulty: 'beginner' },
  { id: 80, term: 'Takeaway', definition: 'Food bought to eat elsewhere', example: 'Let\'s order a takeaway', category: 'daily', difficulty: 'beginner' },

  // EMOTIONS & FEELINGS (15 words)
  { id: 81, term: 'Happy', definition: 'Feeling joy or pleasure', example: 'I\'m so happy to see you', category: 'emotions', difficulty: 'beginner' },
  { id: 82, term: 'Sad', definition: 'Feeling sorrow', example: 'She looks sad today', category: 'emotions', difficulty: 'beginner' },
  { id: 83, term: 'Angry', definition: 'Feeling strong displeasure', example: 'He was angry about the delay', category: 'emotions', difficulty: 'beginner' },
  { id: 84, term: 'Excited', definition: 'Enthusiastic and eager', example: 'I\'m excited about the trip', category: 'emotions', difficulty: 'beginner' },
  { id: 85, term: 'Nervous', definition: 'Anxious or worried', example: 'I\'m nervous about the exam', category: 'emotions', difficulty: 'intermediate' },
  { id: 86, term: 'Confused', definition: 'Unable to think clearly', example: 'I\'m confused by these instructions', category: 'emotions', difficulty: 'beginner' },
  { id: 87, term: 'Surprised', definition: 'Feeling unexpected wonder', example: 'I was surprised by the news', category: 'emotions', difficulty: 'beginner' },
  { id: 88, term: 'Disappointed', definition: 'Sad from unmet expectations', example: 'I\'m disappointed with the result', category: 'emotions', difficulty: 'intermediate' },
  { id: 89, term: 'Proud', definition: 'Feeling satisfaction in achievement', example: 'I\'m proud of you', category: 'emotions', difficulty: 'intermediate' },
  { id: 90, term: 'Jealous', definition: 'Envious of others', example: 'Don\'t be jealous', category: 'emotions', difficulty: 'intermediate' },
  { id: 91, term: 'Grateful', definition: 'Feeling thankful', example: 'I\'m grateful for your help', category: 'emotions', difficulty: 'intermediate' },
  { id: 92, term: 'Anxious', definition: 'Worried about something', example: 'I feel anxious about tomorrow', category: 'emotions', difficulty: 'intermediate' },
  { id: 93, term: 'Lonely', definition: 'Feeling isolated', example: 'Sometimes I feel lonely', category: 'emotions', difficulty: 'intermediate' },
  { id: 94, term: 'Frustrated', definition: 'Upset by inability to achieve', example: 'I\'m frustrated with this problem', category: 'emotions', difficulty: 'intermediate' },
  { id: 95, term: 'Relieved', definition: 'Feeling less worried', example: 'I\'m relieved it\'s over', category: 'emotions', difficulty: 'intermediate' },

  // HEALTH & BODY (15 words)
  { id: 96, term: 'Doctor', definition: 'Medical professional', example: 'I need to see a doctor', category: 'health', difficulty: 'beginner' },
  { id: 97, term: 'Hospital', definition: 'Medical treatment facility', example: 'He\'s in the hospital', category: 'health', difficulty: 'beginner' },
  { id: 98, term: 'Medicine', definition: 'Substance to treat illness', example: 'Take this medicine twice daily', category: 'health', difficulty: 'beginner' },
  { id: 99, term: 'Headache', definition: 'Pain in the head', example: 'I have a terrible headache', category: 'health', difficulty: 'beginner' },
  { id: 100, term: 'Fever', definition: 'High body temperature', example: 'I think I have a fever', category: 'health', difficulty: 'beginner' },
  { id: 101, term: 'Prescription', definition: 'Doctor\'s written order for medicine', example: 'Here\'s your prescription', category: 'health', difficulty: 'intermediate' },
  { id: 102, term: 'Allergy', definition: 'Bad reaction to substance', example: 'I have a peanut allergy', category: 'health', difficulty: 'intermediate' },
  { id: 103, term: 'Symptom', definition: 'Sign of illness', example: 'What are your symptoms?', category: 'health', difficulty: 'intermediate' },
  { id: 104, term: 'Treatment', definition: 'Medical care for illness', example: 'The treatment is working', category: 'health', difficulty: 'intermediate' },
  { id: 105, term: 'Injury', definition: 'Physical harm', example: 'He has a knee injury', category: 'health', difficulty: 'intermediate' },
  { id: 106, term: 'Checkup', definition: 'Routine medical examination', example: 'It\'s time for your annual checkup', category: 'health', difficulty: 'intermediate' },
  { id: 107, term: 'Diagnosis', definition: 'Identification of illness', example: 'The diagnosis was flu', category: 'health', difficulty: 'advanced' },
  { id: 108, term: 'Recovery', definition: 'Getting better from illness', example: 'I wish you a speedy recovery', category: 'health', difficulty: 'intermediate' },
  { id: 109, term: 'Pain', definition: 'Physical suffering', example: 'Where does it pain?', category: 'health', difficulty: 'beginner' },
  { id: 110, term: 'Wellness', definition: 'State of good health', example: 'Focus on your wellness', category: 'health', difficulty: 'advanced' },

  // TECHNOLOGY (15 words)
  { id: 111, term: 'Computer', definition: 'Electronic device for data', example: 'My computer is slow', category: 'technology', difficulty: 'beginner' },
  { id: 112, term: 'Internet', definition: 'Global network', example: 'The internet is down', category: 'technology', difficulty: 'beginner' },
  { id: 113, term: 'Website', definition: 'Collection of web pages', example: 'Visit our website', category: 'technology', difficulty: 'beginner' },
  { id: 114, term: 'Password', definition: 'Secret code for access', example: 'I forgot my password', category: 'technology', difficulty: 'beginner' },
  { id: 115, term: 'Download', definition: 'Transfer data to device', example: 'Download the app', category: 'technology', difficulty: 'beginner' },
  { id: 116, term: 'Upload', definition: 'Transfer data from device', example: 'Upload your photo', category: 'technology', difficulty: 'beginner' },
  { id: 117, term: 'Software', definition: 'Computer programs', example: 'Install this software', category: 'technology', difficulty: 'intermediate' },
  { id: 118, term: 'Hardware', definition: 'Physical computer parts', example: 'We need new hardware', category: 'technology', difficulty: 'intermediate' },
  { id: 119, term: 'Update', definition: 'Latest version of software', example: 'Install the latest update', category: 'technology', difficulty: 'beginner' },
  { id: 120, term: 'Backup', definition: 'Copy of data', example: 'Make a backup of your files', category: 'technology', difficulty: 'intermediate' },
  { id: 121, term: 'Virus', definition: 'Malicious software', example: 'My computer has a virus', category: 'technology', difficulty: 'intermediate' },
  { id: 122, term: 'Browser', definition: 'Software to view websites', example: 'Open your browser', category: 'technology', difficulty: 'intermediate' },
  { id: 123, term: 'Email', definition: 'Electronic message', example: 'Send me an email', category: 'technology', difficulty: 'beginner' },
  { id: 124, term: 'Attachment', definition: 'File sent with email', example: 'Check the attachment', category: 'technology', difficulty: 'intermediate' },
  { id: 125, term: 'Cloud', definition: 'Online storage', example: 'Save it to the cloud', category: 'technology', difficulty: 'intermediate' },

 ];

export default vocabularyData;